apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rsync-daemon
  name: rsync-daemon
data:
  rsyncd.conf: |
    log file = /tmp/rsync.log    
    lock file = /tmp/rsync.lock
    pid file = /tmp/rsyncd.pid
    use chroot = no
    reverse lookup = no
    [data]
        read only = false
        strict modes = false
        hosts allow = *
        path = /data
        auth users = demo:rw
        secrets file = /secrets/rsync.secrets
        timeout = 600
        transfer logging = true