apiVersion: v1
kind: Service
metadata:  
  labels:
    app: rsync-daemon
  name: rsync-daemon
  annotations:
    prometheus.io/scrape: 'false'
spec:
  ports:
  - name: tcp
    port: 8873
    targetPort: 8873
  selector:
    app: rsync-daemon    
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      # 10 hours session affinity based upon client IP address
      timeoutSeconds: 36000
  type: LoadBalancer